_config:
  _metadata:
    name: mongodb
    version: 0.4.7
    description: "NoSQL document-oriented database that stores JSON-like documents with dynamic schemas, simplifying the integration of data in content-driven applications."
    template:
      type: "template.caicloud.io/application"
      version: 1.0.0
  controllers:
  - type: Deployment
    controller:
      replica: 1
    containers:
    - image: "cargo.caicloudprivatetest.com/library/mongodb:3.4.4-r5"
      imagePullPolicy: Always
      ports:
      - protocol: TCP
        port: 27017
      mounts:
      - name: storage
        path: /bitnami/mongodb
      env:
      - name: MONGODB_ROOT_PASSWORD
        value: "123456"
      - name: MONGODB_DATABASE
        value: "default"
      - name: MONGODB_USERNAME
        value: "user"
      - name: MONGODB_PASSWORD
        value: "123456"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    volumes:
    - name: storage
      type: Scratch
      source:
        medium: ""
      storage:
        request: 10Gi
        limit: 10Gi
    services:
    - name: "mongodb"
      type: ClusterIP
      export: true
      ports:
      - protocol: TCP
        targetPort: 27017
        port: 27017
