_config:
  _metadata:
    name: redis
    version: 0.4.5
    description: "Open source, advanced key-value store. It is often referred to as a data structure server since keys can contain strings, hashes, lists, sets and sorted sets."
    template:
      type: "template.caicloud.io/application"
      version: 1.0.0
  controllers:
  - type: Deployment
    controller:
      replica: 1
    containers:
    - image: "cargo.caicloudprivatetest.com/library/redis:3.2.9"
      imagePullPolicy: Always
      ports:
      - protocol: TCP
        port: 6379
      mounts:
      - name: storage
        path: /bitnami/redis
      env:
      - name: REDIS_PASSWORD
        value: "123456"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    volumes:
    - name: storage
      type: Scratch
      source:
        medium: ""
      storage:
        request: 10Gi
        limit: 10Gi
    services:
    - name: "redis"
      type: ClusterIP
      export: true
      ports:
      - protocol: TCP
        targetPort: 6379
        port: 6379
