{{ $env := .Values._config.redis.envs.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
type: Opaque
data:
  {{ $env.name }}: {{ $env.value | b64enc | quote }}
