{{ $service := .Values._config.redis.services.redis }}
apiVersion: v1
kind: Service
metadata:
  name: {{ if ne $service.name "" -}} {{ $service.name }} {{- else -}} {{ template "fullname" . }} {{- end }}
spec:
  type: {{ $service.type }}
  ports:
  {{ range $i, $v := $service.ports -}}
  - name: redis{{ $i }}
    protocol: {{ $v.protocol }}
    port: {{ $v.port }}
    targetPort: {{ $v.targetPort }}
    {{ if ne $v.nodePort "" -}} nodePort: {{ $v.nodePort }} {{- end }}
  {{- end }}
  selector:
    app: {{ template "fullname" . }}
