_config:
  _metadata:
    name: mysql
    version: 0.2.5
    description: "Fast, reliable, scalable, and easy to use open-source relational database."
    template:
      type: "template.caicloud.io/application"
      version: 1.0.0
  controllers:
  - type: Deployment
    controller:
      replica: 1
    initContainers:
    - image: "cargo.caicloudprivatetest.com/library/busybox:1.25.0"
      imagePullPolicy: Always
      command:
      - "rm"
      - "-fr"
      - "/var/lib/mysql/lost+found"
      mounts:
      - name: storage
        path: /var/lib/mysql
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    containers:
    - image: "cargo.caicloudprivatetest.com/library/mysql:5.7.14"
      imagePullPolicy: Always
      ports:
      - protocol: TCP
        port: 3306
      mounts:
      - name: storage
        path: /var/lib/mysql
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "123456"
      - name: MYSQL_DATABASE
        value: "default"
      - name: MYSQL_USER
        value: "user"
      - name: MYSQL_PASSWORD
        value: "123456"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    volumes:
    - name: storage
      type: Scratch
      source:
        medium: ""
      storage:
        request: 10Gi
        limit: 10Gi
    services:
    - name: "mysql"
      type: ClusterIP
      export: true
      ports:
      - protocol: TCP
        targetPort: 3306
        port: 3306
