{{ $env := .Values._config.mongodb.envs.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
type: Opaque
data:
  {{ range $v := $env }}
  {{ $v.name }}: {{ $v.value | b64enc | quote }}
  {{ end }}
